import React from 'react';

class ClassExample extends React.Component {
  //argument?
  constructor() {
    //argument?
    super();

    //Becomes useful now to build state
    this.state = {color: "red"};

  }

  changeColor = () => {
    this.setState({color: "blue"});
  }

  render() {
    return (
    //displaying state and then prop variable
    //then inserting a p generated by function
    <div>
      <h2>I am a {this.state.color} {this.props.brand}!</h2>
      <button type="button" onClick={this.changeColor}>Change color</button>
      <p> This is a p element inserted by a function outside of the component{Top()}</p>
    </div>
    );
  }
}

//Not same name as file so does not run unless called; a helper function
function Top() {
  return(
  <p>The p element!</p>
  )
}


export default ClassExample